### PR TITLE
Update documentation for Storage Connection String and add Azure Extension bundle

### PR DESCRIPTION
**Pull request by lastcoolnameleft**
I tried running through the documentation and the Blob Trigger didn't work until I performed the steps listed.

### CODE REVIEW

**Comment by snobu** [comment]
Thanks for catching this! @yokawasa, i believe this is needed for all functions that use a blob trigger/input/output, right? Or any function that touches Azure Storage?

**Comment by snobu** [comment]
@lastcoolnameleft, the [host.json][1] in the root of the function app seems to have the bundles in 
already, which should take effect for all functions under that function app. Did you clone the repo or started from scratch and maybe missed that config file?

If the latter, i believe we should definitely mention why the bundle is in there and link to the `host.json` file for clarity. We should surface this in the root README. All this should avoid suboptimal user experience. Can you please make this change?

[1]: https://github.com/yokawasa/azure-functions-python-samples/blob/master/v2functions/host.json

**Comment by lastcoolnameleft** [comment]
Closing this PR as I realized it was PEBKAC.  (I ran `func host start` in the sub dir (e.g. `blob-trigger-watermark-blob-out-binding`) , which allows the function to start and creates a new host file. once I added the changes, then everything worked for me, but if I would have ran it in the correct directory, that would have fixed my root problem)
Sorry for the inconvenience.  

That said, I think the documentation suggestions you stated would be useful.  Specifying which directory to run in specifically for my case.

**Comment by lastcoolnameleft** [comment]
Created feature request to Function Core tools to reflect issue I encountered due to inconsistent behavior:  https://github.com/Azure/azure-functions-core-tools/issues/1489

**Pull request closed without merging**
